import { useMemo } from "react";

type AppControllerSurfacePropsInput = Record<string, any>;

function useAppControllerSurfaceProps(input: AppControllerSurfacePropsInput) {
  const providerSurfaceProps = useMemo(
    () => ({
      pingHealth: input.handlePingHealth,
      refreshModelProviders: input.handleRefreshModelProviders,
      refreshPlatformModels: input.handleRefreshPlatformModels,
      generateOnce: input.handleGenerateOnce
    }),
    [input.handleGenerateOnce, input.handlePingHealth, input.handleRefreshModelProviders, input.handleRefreshPlatformModels]
  );

  const sidebarSurfaceProps = useMemo(
    () => ({
      serviceScope: input.normalizedServiceScope,
      serviceScopeOptions: input.serviceScopeOptions,
      systemProfile: input.systemProfile,
      selectedServiceScopeLabel: input.selectedServiceScopeLabel,
      workspaceRuntimeFilterOptions: input.workspaceRuntimeFilterOptions,
      filteredSavedWorkspaces: input.filteredSavedWorkspaces,
      orderedSavedWorkspaces: input.orderedSavedWorkspaces,
      savedSessionsCount: input.filteredSavedSessionsCount,
      totalSavedSessionsCount: input.savedSessions.length,
      workspaceManagementEnabled: input.workspaceManagementEnabled,
      showWorkspaceCreator: input.showWorkspaceCreator,
      setShowWorkspaceCreator: input.setShowWorkspaceCreator,
      activeWorkspaceId: input.activeWorkspaceId,
      expandWorkspaceInSidebar: input.navigationActions.expandWorkspaceInSidebar,
      workspaceDraft: input.workspaceDraft,
      setWorkspaceDraft: input.setWorkspaceDraft,
      workspaceRuntimes: input.workspaceRuntimes,
      createWorkspace: input.navigationActions.createWorkspace,
      refreshWorkspaceRuntimes: input.navigationActions.refreshWorkspaceRuntimes,
      uploadWorkspaceRuntime: input.navigationActions.uploadWorkspaceRuntime,
      updateWorkspaceRuntime: input.navigationActions.updateWorkspaceRuntime,
      deleteWorkspaceRuntime: input.navigationActions.deleteWorkspaceRuntime,
      refreshWorkspaceIndex: input.navigationActions.refreshWorkspaceIndex,
      createSession: input.navigationActions.createSession,
      sessionId: input.sessionId,
      sessionRuns: input.sidebarSessionRuns,
      refreshSessionById: input.navigationActions.refreshSession,
      removeSavedSession: input.navigationActions.removeSavedSession,
      renameSession: input.navigationActions.renameSession,
      sessionsByWorkspaceId: input.sessionsByWorkspaceId,
      expandedWorkspaceIds: input.expandedWorkspaceIds,
      expandedSessionIds: input.expandedSessionIds,
      openWorkspace: input.navigationActions.openWorkspace,
      toggleWorkspaceExpansion: input.navigationActions.toggleWorkspaceExpansion,
      toggleSessionExpansion: (targetId: string) =>
        input.setExpandedSessionIds((current: string[]) =>
          current.includes(targetId) ? current.filter((entry) => entry !== targetId) : [targetId, ...current].slice(0, 64)
        ),
      deleteWorkspace: input.navigationActions.deleteWorkspace,
      deleteWorkspacesForRuntime: input.navigationActions.deleteWorkspacesForRuntime,
      storageOverview: input.storageController.storageSurfaceProps.storageOverview,
      storageRedisEnabled: input.storageController.storageSurfaceProps.storageRedisEnabled,
      storageBrowserTab: input.storageController.storageSurfaceProps.storageBrowserTab,
      onStorageBrowserTabChange: input.storageController.storageSurfaceProps.onStorageBrowserTabChange,
      onRefreshStorageOverview: input.storageController.storageSurfaceProps.onRefreshStorageOverview,
      selectedStorageTable: input.storageController.storageSurfaceProps.selectedStorageTable,
      onSelectStorageTable: input.storageController.storageSurfaceProps.onSelectStorageTable,
      storageTableSearch: input.storageController.storageSurfaceProps.storageTableSearch,
      onStorageTableSearchChange: input.storageController.storageSurfaceProps.onStorageTableSearchChange,
      storageTableWorkspaceId: input.storageController.storageSurfaceProps.storageTableWorkspaceId,
      onStorageTableWorkspaceIdChange: input.storageController.storageSurfaceProps.onStorageTableWorkspaceIdChange,
      storageTableSessionId: input.storageController.storageSurfaceProps.storageTableSessionId,
      onStorageTableSessionIdChange: input.storageController.storageSurfaceProps.onStorageTableSessionIdChange,
      storageTableRunId: input.storageController.storageSurfaceProps.storageTableRunId,
      onStorageTableRunIdChange: input.storageController.storageSurfaceProps.onStorageTableRunIdChange,
      storageTableStatus: input.storageController.storageSurfaceProps.storageTableStatus,
      onStorageTableStatusChange: input.storageController.storageSurfaceProps.onStorageTableStatusChange,
      storageTableErrorCode: input.storageController.storageSurfaceProps.storageTableErrorCode,
      onStorageTableErrorCodeChange: input.storageController.storageSurfaceProps.onStorageTableErrorCodeChange,
      storageTableRecoveryState: input.storageController.storageSurfaceProps.storageTableRecoveryState,
      onStorageTableRecoveryStateChange: input.storageController.storageSurfaceProps.onStorageTableRecoveryStateChange,
      onRefreshStorageTable: input.storageController.storageSurfaceProps.onRefreshStorageTable,
      onClearStorageTableFilters: input.storageController.storageSurfaceProps.onClearStorageTableFilters,
      redisKeyPattern: input.storageController.storageSurfaceProps.redisKeyPattern,
      onRedisKeyPatternChange: input.storageController.storageSurfaceProps.onRedisKeyPatternChange,
      redisKeyPage: input.storageController.storageSurfaceProps.redisKeyPage,
      selectedRedisKey: input.storageController.storageSurfaceProps.selectedRedisKey,
      onSelectRedisKey: input.storageController.storageSurfaceProps.onSelectRedisKey,
      onRefreshRedisKeys: input.storageController.storageSurfaceProps.onRefreshRedisKeys,
      storageBusy: input.storageController.storageSurfaceProps.storageBusy,
      storageInspectionEnabled: input.storageInspectionEnabled,
      pingHealth: input.handlePingHealth,
      refreshModelProviders: input.handleRefreshModelProviders,
      refreshPlatformModels: input.handleRefreshPlatformModels,
      modelProviders: input.modelProviders
    }),
    [
      input.activeWorkspaceId,
      input.expandedSessionIds,
      input.expandedWorkspaceIds,
      input.filteredSavedSessionsCount,
      input.filteredSavedWorkspaces,
      input.handlePingHealth,
      input.handleRefreshModelProviders,
      input.handleRefreshPlatformModels,
      input.modelProviders,
      input.navigationActions,
      input.normalizedServiceScope,
      input.orderedSavedWorkspaces,
      input.savedSessions.length,
      input.serviceScopeOptions,
      input.selectedServiceScopeLabel,
      input.sessionId,
      input.sidebarSessionRuns,
      input.sessionsByWorkspaceId,
      input.setExpandedSessionIds,
      input.setShowWorkspaceCreator,
      input.setWorkspaceDraft,
      input.showWorkspaceCreator,
      input.systemProfile,
      input.storageController.storageSurfaceProps,
      input.storageInspectionEnabled,
      input.workspaceDraft,
      input.workspaceManagementEnabled,
      input.workspaceRuntimeFilterOptions,
      input.workspaceRuntimes
    ]
  );

  const runtimeDetailSurfaceProps = useMemo(
    () => ({
      mainViewMode: input.mainViewMode,
      setMainViewMode: input.setMainViewMode,
      setSurfaceMode: input.setSurfaceMode,
      hasActiveSession: input.hasActiveSession,
      currentSessionName: input.currentSessionName,
      currentWorkspaceName: input.currentWorkspaceName,
      inspectorSubtitle: input.inspectorSubtitle,
      latestEvent: input.latestEvent,
      session: input.session,
      workspace: input.workspace,
      workspaceId: input.workspaceId,
      sessionRuns: input.sessionRuns,
      refreshSessionRuns: input.handleRefreshSessionRuns,
      sessionEvents: input.events,
      deferredEvents: input.deferredEvents,
      messageFeed: input.messageFeed,
      refreshRunById: input.handleRefreshRunById,
      refreshRunStepsById: input.handleRefreshRunStepsById,
      openSessionById: input.navigationActions.refreshSession,
      conversationThreadRef: input.conversationThreadRef,
      conversationTailRef: input.conversationTailRef,
      shouldAutoFollowConversationRef: input.shouldAutoFollowConversationRef,
      hasMoreMessages: Boolean(input.messagesNextCursor),
      messagesLoading: input.messagesLoading,
      loadingOlderMessages: input.loadingOlderMessages,
      queuedSessionRuns: input.sessionQueuedRuns,
      loadOlderMessages: input.handleLoadOlderMessages,
      refreshMessages: input.handleRefreshMessages,
      sendMessage: input.handleSendMessage,
      answerAskUserQuestion: input.handleAnswerAskUserQuestion,
      guideMessage: input.handleGuideMessage,
      guideQueuedSessionInput: input.handleGuideQueuedSessionInput,
      guideMessageSupported: true,
      refreshRun: input.handleRefreshRun,
      refreshRunSteps: input.handleRefreshRunSteps,
      cancelCurrentRun: input.handleCancelCurrentRun,
      refreshSessionTerminal: input.refreshSessionTerminal,
      sendSessionTerminalInput: input.sendSessionTerminalInput,
      modelCallTraces: input.modelCallTraces,
      latestModelCallTrace: input.latestModelCallTrace,
      firstModelCallTrace: input.firstModelCallTrace,
      composedSystemMessages: input.composedSystemMessages,
      selectedSessionMessage: input.selectedSessionMessage,
      selectedMessageSystemMessages: input.selectedMessageSystemMessages,
      selectedModelCallTrace: input.selectedModelCallTrace,
      storedMessageCounts: input.storedMessageCounts,
      latestModelMessageCounts: input.latestModelMessageCounts,
      resolvedModelNames: input.resolvedModelNames,
      resolvedModelRefs: input.resolvedModelRefs,
      allEngineTools: input.allEngineTools,
      allEngineToolNames: input.allEngineToolNames,
      allAdvertisedToolNames: input.allAdvertisedToolNames,
      allToolServers: input.allToolServers,
      downloadSessionTrace: input.downloadSessionTrace,
      selectedRunStep: input.selectedRunStep,
      selectedSessionEvent: input.selectedSessionEvent,
      catalog: input.catalog,
      isSwitchingSessionAgent: input.switchingSessionAgentId === input.session?.id && input.pendingSessionAgentName !== null,
      switchSessionAgent: input.handleSwitchSessionAgent,
      isSwitchingSessionModel: input.switchingSessionModelId === input.session?.id,
      updateSessionModel: input.handleUpdateSessionModel,
      triggerWorkspaceAction: input.triggerWorkspaceAction,
      refreshWorkspace: input.handleRefreshWorkspace,
      isRunning: input.hasActiveSessionRun,
      fileManager: input.workspaceFileManager.fileManagerSurfaceProps
    }),
    [
      input.allAdvertisedToolNames,
      input.allEngineToolNames,
      input.allEngineTools,
      input.allToolServers,
      input.catalog,
      input.composedSystemMessages,
      input.currentSessionName,
      input.currentWorkspaceName,
      input.deferredEvents,
      input.downloadSessionTrace,
      input.events,
      input.firstModelCallTrace,
      input.handleAnswerAskUserQuestion,
      input.handleCancelCurrentRun,
      input.handleGuideMessage,
      input.handleGuideQueuedSessionInput,
      input.handleLoadOlderMessages,
      input.handleRefreshMessages,
      input.handleRefreshRun,
      input.handleRefreshRunById,
      input.handleRefreshRunSteps,
      input.handleRefreshRunStepsById,
      input.handleRefreshSessionRuns,
      input.handleRefreshWorkspace,
      input.handleSendMessage,
      input.handleSwitchSessionAgent,
      input.handleUpdateSessionModel,
      input.hasActiveSession,
      input.hasActiveSessionRun,
      input.inspectorSubtitle,
      input.latestEvent,
      input.latestModelCallTrace,
      input.latestModelMessageCounts,
      input.loadingOlderMessages,
      input.mainViewMode,
      input.messageFeed,
      input.messagesLoading,
      input.messagesNextCursor,
      input.modelCallTraces,
      input.navigationActions,
      input.pendingSessionAgentName,
      input.resolvedModelNames,
      input.resolvedModelRefs,
      input.selectedMessageSystemMessages,
      input.selectedModelCallTrace,
      input.selectedRunStep,
      input.selectedSessionEvent,
      input.selectedSessionMessage,
      input.sendSessionTerminalInput,
      input.session,
      input.sessionQueuedRuns,
      input.sessionRuns,
      input.setMainViewMode,
      input.setSurfaceMode,
      input.storedMessageCounts,
      input.switchingSessionAgentId,
      input.switchingSessionModelId,
      input.triggerWorkspaceAction,
      input.workspace,
      input.workspaceFileManager.fileManagerSurfaceProps,
      input.workspaceId
    ]
  );

  const consolePanelProps = useMemo(
    () => ({
      isOpen: input.consoleOpen && input.surfaceMode === "engine",
      entries: input.consoleEntries,
      onEntryInspect: input.handleInspectConsoleEntry,
      openErrors: input.openConsoleForErrors
    }),
    [input.consoleEntries, input.consoleOpen, input.handleInspectConsoleEntry, input.openConsoleForErrors, input.surfaceMode]
  );

  return {
    consolePanelProps,
    providerSurfaceProps,
    runtimeDetailSurfaceProps,
    sidebarSurfaceProps
  };
}

export { useAppControllerSurfaceProps };
